<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>JavaScript</title>

  <script>
    //netflix


    var video = Array()

    video[1] = Array()
    video[1]['nome'] = 'Fullmetal Alchemist'
    video[1]['categoria'] = 'Anime'

    function getVideo(video) {

      try {
        //lógica
        //http
        console.log(video[0]['nome'])
        // quando vc pede o nome ele da erro pois não tem
        // mas se vc deixar só a poição em que está vazia ele da undefined um erro inesperado
      } catch (erro) {
        tratarErro(erro)
        console.log('Agora sim podemos tratar esse erro')
        // throw new Error('Houve um erro mas não se preocupe, estamos trabalhando nisso agora!')
        // o throw interrompe o script e manda uma mensagem personalizada, e ele é para aplicações reativas ou seja ele reagi ao erro, o cath ele deixa o erro e não deixa a aplicação morrer
      } finally {
        console.log('Sempre passa por aqui (try / catch)')
      }

      console.log('A aplicação não morreu')
    }

    function tratarErro(e) {
      console.log(e)
    }
    getVideo(video)
  </script>

</head>

<body>
</body>

</html>